= Technexion Yocto BSP

Host Environment Setup
[source,console]
$: sudo apt-get install gawk wget git-core diffstat unzip texinfo gcc-multilib \
 build-essential chrpath  socat \
 libsdl1.2-dev xterm  sed cvs subversion coreutils texi2html \
 docbook-utils python-pysqlite2 help2man make gcc g++ desktop-file-utils \
 libgl1-mesa-dev libglu1-mesa-dev mercurial autoconf automake groff curl lzop asciidoc

For Ubuntu 12.04 host setup only:
[source,console]
$: sudo apt-get install uboot-mkimage

For Ubuntu 14.04 host setup only:
[source,console]
$: sudo apt-get install u-boot-tools

To get the BSP you need to have `repo` installed and use it as:

Install the `repo` utility:

[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

[source,console]
$: PATH=${PATH}:~/bin
$: mkdir edm-yocto
$: cd edm-yocto
$: repo init -u https://github.com/TechNexion/edm-yocto-bsp.git -b dizzy_3.14.52-1.1.0_GA
$: repo sync

At the end of the commands you have every metadata you need to start work with.

To start a simple image build:

[source,console]
$: DISPLAY=hdmi720p MACHINE=edm-fairy-imx6 source edm-setup-release.sh -b build-x11 -e x11
$: bitbake fsl-image-qt5

`DISPLAY` parameters can be:
`lvds7`, `hdmi720p`, `hdmi1080p`, `lcd`, `lvds7_hdmi720p`, `custom`

`MACHINE` parameters can be:
`edm-fairy-imx6`, `edm-toucan-imx6`, `edm-goblin-imx6sx`, `picosom-dwarf-imx6`, `tek3-imx6`
