= TechNexion Yocto 2.2 morty 4.9.y GA BSP

This BSP is a TechNexion release providing support NXP i.mx series processors


[source,console]
$: mkdir ~/bin
$: curl http://commondatastorage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
$: chmod a+x ~/bin/repo

Download the BSP source:

For NXP i.mx8mq SOC, e.g.,PICO-IMX8M:
[source,console]
$: PATH=${PATH}:~/bin
$: mkdir edm_yocto
$: cd edm_yocto
$: repo init -u https://github.com/TechNexion/edm-yocto-bsp.git -b morty_4.9.y_GA -m imx-4.9.51-8mq_ga.xml
$: repo sync -j8


== Configurations for setup script

`“MACHINE”` is the target of build. It usually corresponds to the name of SOM or SBC.

For more information, please check the file under `“sources/meta-edm-bsp-release/conf/machine”`.

`“DISPLAY”` is the disply type. This option only works on i.mx6 (i.mx6 Solo/Dual Lite/Dual/Quad) SOMs and doesn’t work for i.mx6ul, i.mx6sx and i.mx7.

`“BASEBOARD”` is the baseboard type.

`“-b”` specify the build directory.

`“-e”` sets the graphical back end for frame buffer and direct fb images. X11 is default if no backend is set.

.Build configurations for supported hardware
|===
|Parameter |Available options|Description

|MACHINE
|pico-imx8m
|PICO-IMX8M
(i.MX8M Quad)

|DISPLAY
|lvds7
|7 inch 1024x600 LVDS panel

|(Parameter "DISPLAY" only works on i.mx6)
|hdmi720p
|1280x720 HDMI

|
|hdmi1080p
|1920x1080 HDMI

|
|lcd
|5 inch/7 inch 800x480 TTL parallel LCD panel

|
|lvds7_hdmi720p
|Dual display output to both 7 inch LVDS and HDMI

|
|custom
|Reserved for custom panel

|DISTRO
|fsl-imx-x11
|Only X11 graphics

|
|fsl-imx-wayland
|Wayland weston graphics

|
|fsl-imx-xwayland
|Wayland graphics and X11. X11 applications using EGL are not supported

|
|fsl-imx-fb
|Frame Buffer graphics - no X11 or Wayland

|-b
|<build dir>
|Assign the name of build directory
|===

.Choosing Yocto target image
|===
|Image name |Target

|core-image-minimal
|A small image that only allows a device to boot

|core-image-base
|A console-only image that fully supports the target device
hardware

|core-image-sato
|An image with Sato, a mobile environment and visual style
for mobile devices. The image supports X11 with a Sato
theme, Pimlico applications. It contains a terminal, an
editor and a file manager

|fsl-image-machine-test
|An FSL Community i.MX core image with console
environment - no GUI interface

|fsl-image-validation-imx
|Builds an i.MX image with a GUI without any Qt content.

|fsl-image-qt5-validation-imx
|Builds an opensource Qt 5 image. These images are only
supported for i.MX SoC with hardware graphics. They are
not supported on the i.MX 6UltraLite, i.MX 6UltraLiteLite,
and i.MX 7Dual.
|===

== Build Yocto for TechNexion target platform
=== For PICO-IMX8M
*XWayland image for HDMI output:*
[source,console]
$: DISTRO=fsl-imx-xwayland MACHINE=pico-imx8m source edm-setup-release.sh -b build-xwayland
$: bitbake fsl-image-qt5-validation-imx
or
$: bitbake fsl-image-validation-imx

*Wayland image for HDMI output:*
[source,console]
$: DISTRO=fsl-imx-wayland MACHINE=pico-imx8m source edm-setup-release.sh -b build-wayland
$: bitbake fsl-image-qt5-validation-imx
or
$: bitbake fsl-image-validation-imx


== QTWebkit
To start to go to /usr/share/qt5/examples/webkitwidgets/browser and run browser

== Qt
Note that Qt has both a commercial and open source license options.  Make the decision about which license
to use before starting work on custom Qt applications.  Once custom Qt applications are started with an open source
Qt license the work can not be used with a commercial Qt license.  Work with a legal representative to understand
the differences between each license.   Default builds use an open source Qt license.

Note Qt is not supported on i.MX 6UltraLite and i.MX 7Dual. It works on X11 backend only but is not a supported feature.

== Image Deployment
When build completes, the generated release image is under “${BUILD-TYPE}/tmp/deploy/images/${MACHINE}”:
$: bzip2 -fd fsl-image-XXX.rootfs.sdcard.bz2
"fsl-image-XXX.rootfs.sdcard"
Just flash this image into your target board to deploy yocto.